project:
  type: website
  output-dir: docs

website:
  title: "Tutorial test using Quarto"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: litera 
    css: styles.css
    toc: true



